### ISSUE TITLE
Timezone fixed to Australia/Sydney

### ISSUE THREAD

**Issue by paul-watkins-croud** [CroudSupport/recurring_task_scheduler#1]
https://github.com/CroudSupport/recurring_task_scheduler/blob/e73aa62ad6241c5f28b6e962aa602d0d201f07eb/src/Model/ScheduleEvent.php#L88

In scopeTodaysEvents the timezone is fixed, but needs to passed into the scope.

**Comment by jimrobinson-croud** [comment]
Fixed in release 2.0.4 
#2
